# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'Contact', url: 'contact.html'}
- {name: 'Teaching', url: 'teaching.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'fa-brands fa-github',     link: 'https://github.com/donkoralle'}
- {icon: 'fa-brands fa-mastodon',    link: 'https://mastodon.social/@Kamihoeferl'}
- {icon: 'fa-brands fa-linkedin',   link: 'https://www.linkedin.com/in/karl-michael-h%C3%B6ferl-77a313325/'}
- {icon: 'fa-regular fa-envelope',   link: 'mailto:donkoralle@posteo.de'}
# - {icon: 'rss-square', link: '/feed.xml'}
- {icon: 'fa-solid fa-square-rss', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
